### ISSUE TITLE
Get System-Wide Flow and Runoff Accumulation Volume

### ISSUE THREAD

**Issue by andredaa** [aerispaha/swmmio#120]
Hello!
I just found your tool yesterday and find it amazing to use. I already used it to manipulate input files for different scenarios :)
I am not a stormwater expert, but programmer and would like to ask a question - rather than issue.

But there is one thing I cannot figure out from reading the docs.
Is there a way to obtain system-wide results from the rpt ? 
![image](https://user-images.githubusercontent.com/4631906/107775173-418c9980-6d40-11eb-92be-6851df5997ef.png)

I assume pyswmm equivalent is the SystemModule ?
https://pyswmm.readthedocs.io/_/downloads/en/stable/pdf/ (S.67)

We are interested in a time series for the system-wide runoff . 

Thanks for any help.
Best
Andre

**Comment by aerispaha** [comment]
Hello @andredaa!  I'm glad to hear you've found some uses for swmmio!  

Regarding system-wide time series results, there isn't an out-of-the-box way of doing this yet with swmmio. Time series results from the `rpt` file is possible, but it's not a main focus of swmmio right now. I find the `rpt` to be most useful for getting simulation summary stats (e.g. total flow at each node) , and using the binary `out` files for timeseries results. 

That said, you could compute system-wide runoff stats by post processing the subcatchments results with a pandas command or two. Something like this: 
```python
# import example swmmio.Model with results
from swmmio.examples import spruce
subs = spruce.subcatchments.dataframe

# then use pandas to compute the system wide stats
subs[['TotalRunoffIn', 'TotalRunoffMG']].sum()
```
```
TotalRunoffIn    2.45
TotalRunoffMG    0.28
dtype: float64
```

**Comment by dickinsonre** [comment]
I am commenting out of place but if you read the .OUT file the system output parameter are already in the .out file.  The total Subcatchment Runoff values are already then.

**Comment by andredaa** [comment]
Thank you @aerispaha & @dickinsonre ! 
This helps a great deal!
@dickinsonre : Am I right that there it is not possible to open the .out file without the GUI? We are looking to fully automate the process, without using the GUI at all. Or is there a way to read the .out? (I ignored the .out file this far, as I was told it is a binary file). 

Best
Andre

**Comment by andredaa** [comment]
@aerispaha : Sorry - very simple question for understanding.
Are the values in the system-wide run-off series just a simple sum of the values of all subcatchments' time-series?
Thanks for your help!

**Comment by dickinsonre** [comment]
I thought the purpose of SWMMIO, PySWMM, and others was to read and convert the OUT file (binary data) to a human usable format?

**Comment by aerispaha** [comment]
Hey @andredaa, here are couple responses to your questions: 

>  Am I right that there it is not possible to open the .out file without the GUI? 

There are programmatic ways to open the out files without the GUI. We considered including this in the roadmap for `swmmio` (see #60) , but decided to pause that effort. I personally think that is a good fit for `swmmio`, but it's not currently in the scope. That said, the [swmm-output](https://github.com/OpenWaterAnalytics/swmm-python/releases/tag/v0.1.0-alpha) tool is what I'd recommend. 


> Are the values in the system-wide run-off series just a simple sum of the values of all subcatchments' time-series?

Yes, if you have a model with subcatchments, the total (i.e. systemwide) runoff will equal the sum of runoff from each subcatchment.

**Comment by andredaa** [comment]
Amazing!
Thank you guys a lot. I really appreciate your help.
I'll close the issue. :)
