### ISSUE TITLE
Errors when overwrite the [OPTIONS] Sections

### ISSUE THREAD

**Issue by timebridge** [aerispaha/swmmio#121]
The current replace_inp_section cannot correctly overwrite the [OPTIONS] section. Instead, it will insert a new section from datasets above the previous old parameter. 

This probably because pandas data frame is not the exactly same as the [OPTIONS] rows (e.g. more spaces and older), such that the new data will be considered as new information and thus being inserted above other than overwrite?

Might be also because SWMM engine version I used (5.1.015)?

**Comment by timebridge** [comment]
I figured out the reason for this bug. 
Please consider use at replace_inp_section function:
            if (found_section and any(("["+str(es)+"]") in line for es in sections.keys()) and modified_section_header not in line):
                found_next_section = True
As there are words like "REPORT" and "Infiltration" in [OPTIONS] section, so they are mistreated as the found NEXT Section, and Therefore, the content after these marked next section were added. So the solution is to add "[]" as part of the criteria when identifying headers,  then problem is solved

**Comment by aerispaha** [comment]
@timebridge, great catch and fix! 

Feel free to submit a pull request with this fix. Otherwise, I can get this into our next release.

**Comment by aerispaha** [comment]
@timebridge, this issue was resolved in today's v0.4.8 release, thanks to you and @jackieff!
