### ISSUE TITLE
KeyError 'Horton' while extracting data  

### ISSUE THREAD

**Issue by Rachelluwee** [aerispaha/swmmio#131]
Hi Aerispaha,

one error occurred when I run the swmmio for data extraction,  which is "no KeyError: 'Horton'. More details are shown as followed:
![image](https://user-images.githubusercontent.com/37835436/165745623-6b00f9bf-b394-403c-a8b8-b69a85ea3b19.png)
Did I set the wrong parameter in my model in SWMM or there are some other reasons. Could you help me with this out?

**Comment by aerispaha** [comment]
@Rachelluwee thanks for finding this potential bug! Can you share the model inp file that you are working with, or provide an example that will reproduce this error?

**Comment by Rachelluwee** [comment]
> @Rachelluwee thanks for finding this potential bug! Can you share the model inp file that you are working with, or provide an example that will reproduce this error?

Sure. Just sent you an E-Mail with .inp file in attachment. ;)

**Comment by aerispaha** [comment]
Hey @Rachelluwee!  After some testing, I think the main issue is that your .inp file has the `INFILTRATION` option set to `Horton` when it should be uppercase `HORTON`. Infiltration can be set to one of several algorithms by setting `INFILTRATION` with any of the following strings: 
- CURVE_NUMBER
- GREEN_AMPT
- HORTON
- MODIFIED_GREEN_AMPT
- MODIFIED_HORTON 

Admittedly, it's a bit lame that `swmmio` stumbles to handle `Horton`. We could make this a bit more forgiving by casting any infiltration algorithm string to upper case in the backend. This way we could get silly and use `gReEn_aMpT` if we wish. But for now, things should work for you if you just use all caps. 

Note, there are some larger issues going on with swmmio when using Python 3.8 and above. This is being addressed in #137. I recommend working in Python 3.7 until we make our next release.

**Comment by Rachelluwee** [comment]
> Hey @Rachelluwee! After some testing, I think the main issue is that your .inp file has the `INFILTRATION` option set to `Horton` when it should be uppercase `HORTON`. Infiltration can be set to one of several algorithms by setting `INFILTRATION` with any of the following strings:
> 
> * CURVE_NUMBER
> * GREEN_AMPT
> * HORTON
> * MODIFIED_GREEN_AMPT
> * MODIFIED_HORTON
> 
> Admittedly, it's a bit lame that `swmmio` stumbles to handle `Horton`. We could make this a bit more forgiving by casting any infiltration algorithm string to upper case in the backend. This way we could get silly and use `gReEn_aMpT` if we wish. But for now, things should work for you if you just use all caps.
> 
> Note, there are some larger issues going on with swmmio when using Python 3.8 and above. This is being addressed in #137. I recommend working in Python 3.7 until we make our next release.

Thanks for the feedback! Good to know! I will test once again using Green_Ampt method :)
