### ISSUE TITLE
Weir Dataframe Problem

### ISSUE THREAD

**Issue by DanielaRodriguez834** [aerispaha/swmmio#132]
Hello!

When creating a data frame with the weirs it does not allow it since not all the columns in the weir section of the input file are full.
In my model I have no road weirs, therefore I have no information for "RoadWidth", "RoadSurf", and "Coeff. Curve", and I have left them blank. However, when trying to create the data frame I get an error. Here I send the pictures.
Any idea how to solve the problem? thank you!

![image](https://user-images.githubusercontent.com/107396204/173311865-06e6a035-d425-4362-b931-278532727709.png)
![image](https://user-images.githubusercontent.com/107396204/173312069-64552e2f-4fdf-4259-bc57-bf6f6cc23272.png)
![image](https://user-images.githubusercontent.com/107396204/173312128-5cffdb34-c166-4162-8368-1d45aec88007.png)

**Comment by aerispaha** [comment]
@DanielaRodriguez834 thanks for identifying this issue! Are you able to share an example inp file that will reproduce this issue? I'd like to investigate this in my environment.

**Comment by aerispaha** [comment]
@DanielaRodriguez834 FYI, I believe this issue will be resolved with #130. I've been able to reproduce your issue in multiple environments and hopefully have a fix pending.
