### ISSUE TITLE
export_to_shapefile

### ISSUE THREAD

**Issue by rhc123123** [aerispaha/swmmio#134]
The following error occurs when performing a transformation SHP on a very simple model:

mymodel.export_to_shapefile('D:/admin')
error:
  File "E:\APP\Anaconda3\envs\swmmio_env\lib\site-packages\swmmio\utils\spatial.py", line 219, in write_shapefile
    w.line(parts=[row.coords])

TypeError: line() got an unexpected keyword argument 'parts'

**Comment by aerispaha** [comment]
@rhc123123 thanks for identifying this issue! I believe this is due to an API change in `pyshp`. Regardless, I think i have a patch to this over in #138 .
