### ISSUE TITLE
mymodel.inp.inflows

### ISSUE THREAD

**Issue by rhc123123** [aerispaha/swmmio#135]
hello！
I have successfully imported my model and can make calls to other properties in the INP module, but there are still some problems with "inp.inflows" . Error is as follows:

 
File "pandas\_libs\parsers.pyx", line 945, in pandas._libs.parsers.TextReader._convert_column_data

ParserError: Too many columns specified: expected 8 and found 6

**Comment by aerispaha** [comment]
Hey @rhc123123, thanks for raising this issue! I believe this was fixed back in v0.4.10, accordingly, I'm going to close this issue. Let me know if the issue still persists for you.
