### ISSUE TITLE
model.inp.headers gives "UnboundLocalError: local variable 'h' referenced before assignment"

### ISSUE THREAD

**Issue by MortenGrum** [aerispaha/swmmio#141]
Hi

I get the following error when I try to call/access  `model.inp.headers`: 

  ```
File "C:\Users\morte\Documents\python_envs\swmmgo_env\lib\site-packages\swmmio\core.py", line 570, in headers
    self._inp_section_details = get_inp_sections_details(self.path,
  File "C:\Users\morte\Documents\python_envs\swmmgo_env\lib\site-packages\swmmio\utils\text.py", line 231, in get_inp_sections_details
    found_sects[h] = OrderedDict(columns=['blob'])
UnboundLocalError: local variable 'h' referenced before assignment
```

Other tables like junctions, name, subareas, subcatchments and timeseries work just fine.

I'm running swmmio version 0.4.10 with following dependencies:

Requirement already satisfied: swmmio==0.4.10 in ...\site-packages (0.4.10)
Requirement already satisfied: pyshp==2.1.0 in ...\site-packages (from swmmio==0.4.10) (2.1.0)
Requirement already satisfied: Pillow>=6.2.0 in ...\site-packages (from swmmio==0.4.10) (9.0.0)
Requirement already satisfied: numpy>=1.16.4 in ...\site-packages (from swmmio==0.4.10) (1.23.4)
Requirement already satisfied: pandas>=0.24.2 in ...\site-packages (from swmmio==0.4.10) (1.3.5)
Requirement already satisfied: geojson>=2.4.1 in ...\site-packages (from swmmio==0.4.10) (2.5.0)
Requirement already satisfied: pyyaml>=3.12 in ...\site-packages (from swmmio==0.4.10) (6.0)
Requirement already satisfied: networkx<3,>=2.3 in ...\site-packages (from swmmio==0.4.10) (2.6.3)
Requirement already satisfied: python-dateutil>=2.7.3 in ...\site-packages (from pandas>=0.24.2->swmmio==0.4.10) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in ...\site-packages (from pandas>=0.24.2->swmmio==0.4.10) (2021.3)
Requirement already satisfied: six>=1.5 in ...\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->swmmio==0.4.10) (1.16.0)

Any ideas?

Thanks in advance.
Morten

**Comment by aerispaha** [comment]
Hey @MortenGrum, thanks for raising this issue! I believe this will be fixed in #160.
