### ISSUE TITLE
error in spatial.py 

### ISSUE THREAD

**Issue by marcoalicera** [aerispaha/swmmio#15]
I am trying it and after installation in an Anaconda environmental i got this error when running the first line
`from swmmio import swmmio`

I got an error in the file spatial.py in line 1
`from definitions import ROOT_DIR`
error:
`ImportError: No module named definitions`

**Comment by aerispaha** [comment]
@marcoalicera, what version of Python are you using in your conda environment? swmmio has been developed only in a Python 2.7 environment so far.

**Comment by marcoalicera** [comment]
I am using Python 2.7.
I installed swmmio with `pip.main(['install','swmmio'])` and I can see that the folder where swmmio is (`...\AppData\Local\Continuum\anaconda2\Lib\site-packages\swmmio`) does not have the file definition.py.
If it does not come with the installation, should I create my own one? and where should I save it?

**Comment by marcoalicera** [comment]
I copied the file in `utils` and worked through the line `from swmmio import swmmio`.
I could also create a swmmio model object and print out the head of nodes as test.

I have no idea how the packaging works, but the file definitions.py should be included in the installation or document how to create it in order to close the case.

Thanks for such an intersiting project anyway!

**Comment by aerispaha** [comment]
Hey @marcoalicera, glad you seem to have gotten things working. You should've been able to install swmmio with a simple `pip install swmmio`. Or if you wanted the latest code, you can clone the repo and run `python setup.py install`.

**Comment by marcoalicera** [comment]
I had a similar problem when runing `from swmmio.graphics import swmm_graphics as sg`, I went through  it by pasting `definition.py` in the folder `\graphics` , as I did in `\utils`, but that is not a real solution.

As mentioned, I have installed swmmio with `pip.main(['install','swmmio'])` in the python prompt, which should be the very same as `pip install swmmio` in the console.

**Comment by schoeller** [comment]
Hi, thanks for this project. I encountered an error similar to yours. In order to resolve I created a file <code>utils/definitions.py</code> and pasted the following lines into it:

<code>
import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
</code>
