### ISSUE TITLE
create_dataframeINP only works with Green & Ampt infiltration model

### ISSUE THREAD

**Issue by kristianfoerster** [aerispaha/swmmio#23]
When working with the create_dataframeINP function in dataframes.py, it always inserts the header (column definitions) of the Green-Ampt model in the data frame. This seems to happen since the inp_header_dict dictionary (in sectionheaders.py) only provides the parameters of the Green & Ampt model:

'[INFILTRATION]':'Subcatchment Suction HydCon IMDmax'

As a workaround, I defined a simple function that checks the infiltration model from the options section and adjusts the header definition for infiltration accordingly:

``dict_inf_headers = {'GREENAMPT':    ['Subcatchment','Suction','HydCon','IMDmax'],
                        'HORTON':       ['Subcatchment','MaxRate','MinRate','Decay','DryTime',' MaxInfil]'],
                        'CURVE_NUMBER': ['CurveNum','','DryTime']}``

**Comment by kristianfoerster** [comment]
Sounds good! :-) Thanks!

**Comment by aerispaha** [comment]
Hey @kristianfoerster, FYI this is being resolved in the upcoming v0.4.0 release!
