### ISSUE TITLE
Possible Collaboration

### ISSUE THREAD

**Issue by bemcdonnell** [aerispaha/swmmio#3]
Hi @aerispaha, you have pulled together a great collection of tools here! Great work! I wanted to mention that there might be possible avenues of collaboration on some of my tools which are under development. 
1. For running models we have pyswmm https://github.com/OpenWaterAnalytics/pyswmm 
   This tool currently provides a pythonic interface to running SWMM. We are in the early stages of adding an Input API to SWMM (https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/InputAPI) so that we can expose hydraulic and hydrologic data read in from an *.inp file.  The "finished" version of this tool will enable optimization.
2. For rapidly pulling data out of the binary output file, you might consider looking at SWMMOutputAPI https://github.com/bemcdonnell/SWMMOutputAPI
   This tool provides a nice python interface to the binary output file.

**Comment by aerispaha** [comment]
Hey @bemcdonnell thanks for the kind words! And thanks for sharing your projects -  I agree there may be ways for us to collaborate. After a quick review, I can say definitely that the binary reader would be of great value and I'm eager to check out the pyswmm interface. We probably are working through many of the same issues.

My immediate goal for myself (and swmmio) is to become fluent with pythonic packaging conventions (I just pushed things to PyPi yesterday!), and updating/improving documentation, especially the swmmio readme.  In the meantime,  I will keep your projects in mind and consider ways we can help each other.
