### ISSUE TITLE
Sample model to test

### ISSUE THREAD

**Issue by knraj** [aerispaha/swmmio#39]
Hi,
Could you please forward the sample test swmm model for which results are displayed in the docs of github repo
Thanks!

**Comment by aerispaha** [comment]
Hi @knraj! Unfortunately I can't share that original model that was used to generate visualizations in the README. There are few sample models in the `swmmio/swmmio/tests/data` directory that you can run tests on. If you have a more interesting model that you can share to include in the tests, I encourage you contribute it to the project!
