### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bemcdonnell** [aerispaha/swmmio#4]
@aerispaha maybe I have overlooked something but is there some place where this code is documented with examples? It looks like it has plenty of nice features but I'm not entirely sure how to use them.

**Comment by aerispaha** [comment]
hey @bemcdonnell, unfortunately you haven't overlooked anything. Documentation is pretty lacking (limited to some docstrings and the README), but it is high on my priority list. I was planning on hosting documentation on readthedocs.org and hoping I could automate the process of updating docs. Does that make sense?

In the meantime, feel free to reach out if you have specific questions.
