### ISSUE TITLE
invalid import in swmmio.utils.modify_model

### ISSUE THREAD

**Issue by kristianfoerster** [aerispaha/swmmio#51]
When calling import swmmio.utils.modify_model (needed to run the function replace_inp_section()) an import exception is thrown... This seems to be related to another import in version_control.

**Comment by aerispaha** [comment]
Hi @kristianfoerster, thanks for finding this issue. This should be fixed in the 0.3.5 release, coming in a few minutes if all things go to plan 😄. You can checkout the relevant changes in #52.
