### ISSUE TITLE
add easy read access to SWMM .out files 

### ISSUE THREAD

**Issue by aerispaha** [aerispaha/swmmio#60]

**Comment by aerispaha** [comment]
@bemcdonnell , @jennwuu I'd like to use the [swmm-output](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/develop/tools/swmm-output) tool from OWA SWMM to develop an easy interface with swmmio to read stuff from out files. 

Are there any plans to publish swmm-output to pypi so we can use it as a dependency? If not, should I just copy that code into swmmio?

**Comment by bemcdonnell** [comment]
I think the plan is to release swig wrapped SWMMOutput/SWMM5 as a low-level interface package to PYPI.  This would give pyswmm something to sit on top of instead of having a sustained low-level API.  In the spirit of separating concerns, I think keeping these dependencies separate is a good idea for longer term planning. Just my thoughts

**Comment by aerispaha** [comment]
Closing this issue as this is out of scope `swmmio`, unless we change our minds in the future 😉

**Comment by jennwuu** [comment]
@aerispaha it would be cool if we can pull byte data from .out file to be interpreted by swmmio :o

**Comment by bemcdonnell** [comment]
#separateconcerns :-P

**Comment by dickinsonre** [comment]
Confused - i thought the primary purpose of SWMMIO and other programs WAS to read the OUT binary file.

**Comment by aerispaha** [comment]
The intended scope for swmmio is to be a programmatic interface to SWMM5 models, including parsing models and results as well as editing and diffing models with Python. When I opened this issue originally, I was thinking that it made sense to include access to data in the out files. Right now there is coverage for the INP and RPT files.

I closed this issue based on @bemcdonnell's suggestion that the out file be managed in a different code base. I'm open to whatever the community thinks makes sense though. 

Personally, I've fumbled around a few times rewriting logic with the swmm-output tool and could envision a world where we could use swmmio to make that process more convenient. This was the world I envisioned when opening this issue:

```python
m = swmmio.Model('my-model-1.inp')

# work with INP and RPT data 
links = m.links
links.dataframe.MaxQ 
links.geodataframe.to_file('links.shp')

# get RPT data
m.rpt.node_flooding

# get/set INP data
m.inp.junctions['InvertElev'] += 2 
m.inp.save('my-model-2.inp')

# retrieve timeseries results from out 
flow_j1 = m.out.total_inflow['J1']
...
```

**Comment by bemcdonnell** [comment]
I wish SWMMIO would include the "Do All My Work" Button.. @aerispaha, how is that coming along :-D
