### ISSUE TITLE
error "no module named swmmio"

### ISSUE THREAD

**Issue by algchyhao** [aerispaha/swmmio#61]
I have pip install swmmio and when I run "python -m swmmio ..." it prompts "from swmmio.swmmio import Model \\ no module named swmmio". I tried both python 2.7 and python 3.7, what could be the problem please?

Update:
main.py
line 3
modify
from .swmmio import Model
to
from swmmio import Model
solved the problem.

**Comment by algchyhao** [comment]
__main__.py
line 3
modify
from .swmmio import Model
to
from swmmio import Model
solved the problem.

**Comment by aerispaha** [comment]
@algchyhao thanks for identifying this issue! Can you please submit a pull request with your changes?

**Comment by algchyhao** [comment]
@aerispaha Sure
