### ISSUE TITLE
move reporting.visualize module

### ISSUE THREAD

**Issue by aerispaha** [aerispaha/swmmio#76]
This is a half-baked single function module that should be removed.

**Comment by aerispaha** [comment]
@dickinsonre, you like this `swmmio.reporting.visualize.create_map` function? What it does right now is visualize the diff between two models in a local Mapbox powered interactive map. This is cool, but the function has a lot of hard coded things and also feels out of place in the reporting module.

If we want to keep this function alive, I propose that it be a bit more generalized, given a unit test, and moved to the graphics module. Does that make sense?

**Comment by dickinsonre** [comment]
Yes, that does make sense, @aerispaha
