### ISSUE TITLE
Visualize the SWMM model structures

### ISSUE THREAD

**Issue by Jiadalee** [aerispaha/swmmio#79]
Hi, I want to visualize a SWMM model by highlighting some junctions. For example, I 'd like to highlight J1, J2, and J3 with red color, and make the other nodes gray. Can swmmio do this visualization? Anyone can give me some suggestions? Thanks

**Comment by aerispaha** [comment]
Hi @Jiadalee! There is a similar example in the readme file to your use case. Here's a more specific example that works by setting the visual parameters of the nodes by changing the `draw_color`: 

```python
# instantiate a swmmio model object
from swmmio.tests.data import MODEL_FULL_FEATURES__NET_PATH
m = swmmio.Model(MODEL_FULL_FEATURES__NET_PATH)

# Pandas dataframe with node data
nodes = m.nodes()

# set the visual parameters of the nodes with pandas logic 
nodes['draw_color'] = '#787882' #grey, default node color
nodes.loc[['J1', 'J2', 'J3'], 'draw_color'] = '#ff0000' #red
nodes['draw_size'] = 20 # increase size to make the color change obvious 

# draw the model 
sg.draw_model(conduits=m.conduits(), nodes=nodes, file_path='my-img.png')
```
![image](https://user-images.githubusercontent.com/6521360/80151499-c8893f00-857f-11ea-90e5-dc38c946f4db.png)
