### ISSUE TITLE
dataframe_from_rpt fails if more than one element is provided in the section

### ISSUE THREAD

**Issue by kristianfoerster** [aerispaha/swmmio#93]
Starting with version 0.4.0 `dataframe_from_rpt` only works properly if only one element exists in the corresponding section. If there are more than one element (e.g., subcatchments), the returned `pd.DataFrame` object is invalid, since it includes the results of all elements as well as the string comments between the time series. I was wondering if it's worth to add the `element_id` argument to the function call (as it was available in swmmio-0.3.x. Thank you!

**Comment by aerispaha** [comment]
Thanks for catching this @kristianfoerster!  I think I have a fix to restore this feature in the dev branch [here](https://github.com/aerispaha/swmmio/commit/efc31e20b969d07b2d569914684c21d4a705be89#diff-07facb9c6fa13df1d105d88d73edf6f6R71-R83)
