### ISSUE TITLE
Trying to install version 0.4.0

### ISSUE THREAD

**Issue by pdim21** [aerispaha/swmmio#99]
I'm trying to install version 0.4.0 but the following message is returned:

Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    long_description=get_description(),
  File "setup.py", line 27, in get_description
    data = f.read()
  File "C:\Users\pdimas\AppData\Local\Programs\Python\Python38\lib\encodings\cp1253.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 9931: character maps to <undefined>

**Comment by aerispaha** [comment]
Hey @pdim21 thanks for finding this issue. Potentially this is a bug introduced by using Python 3.8. Unit tests right now are only set up for 3.6 and 3.7. 

For now, you could try working in a Python 3.7 environment.

**Comment by pdim21** [comment]
@aerispaha thanks for your reply. After some searching the workaround was to downgrade to swmmio 0.3.7 and specify an encoding parameter in line nr. 26 of setup.py as follows:
```
def get_description():
    """Get long description."""
    with open(os.path.join(HERE, 'README.md'), 'r', encoding='utf8') as f:
        data = f.read()
    return data
```

**Comment by aerispaha** [comment]
Interesting. Does it work with v0.4.4 by including the `encoding='utf8'` argument to the `open()` call? If so, please submit a PR and we'll include your fix in the next release.

**Comment by pdim21** [comment]
I didn't have the time to check it out. In case I try it I will let you know though.
